### PR TITLE
Adding Recursive Bin Search + quick sort in c++

### PR DESCRIPTION
**Pull request by nathalia-b**
### Checklist

Pick at least one of the three options

- [x] Added my name to the `CONTRIBUTORS.md` file
- [ ] Added my profile page to the `profiles` directory
- [x] Added my favourite Data Structure in my favourite language to the respective language folder

### CODE REVIEW

**Comment by nathalia-b** [comment]
I beg your pardon, but where do you want me to put my name on?

**Comment by santoshvijapure** [comment]
> I beg your pardon, but where do you want me to put my name on?

At the top of the program  file  : ]
```c++
// LANGUAGE: c++
// ENV: gcc
// AUTHOR: Santoshvijapure
// GITHUB: https://github.com/santoshvijapure

#include <iostream>
using namespace std; 
int stack[100], n=100, top=-1;
void push(int val) {
```
like this  : )

**Comment by nathalia-b** [comment]
Oh, alright! I totally forgot to do that! :) Thank you for explaining.

**Comment by santoshvijapure** [comment]
your welcome :)
xD

**Pull request merged**
